version: '3.8'
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: hcdb
      POSTGRES_USER: hcuser
      POSTGRES_PASSWORD: hcpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
